

# This file was auto-generated by the framework. You can add data models or change the existing ones
import app.db.models as models
import app.db.views as views

from app.fastapi import api as fastapi

