packages:
  - "apps/*"
  - "packages/*"
  - "scripts"

catalog:
  "@clickhouse/client": "1.12.1"
  "@iarna/toml": "3.0.0"
  "@types/chai": "4.3.20"
  "@types/hast": "3.0.4"
  "@types/mocha": "10.0.10"
  "@types/node": "^20"
  axios: "1.7.9"
  chai: "4.5.0"
  github-slugger: "2.0.0"
  mermaid: "11.12.0"
  mocha: "10.8.2"
  ts-node: "10.9.2"
  typescript: "5.9.3"
  yaml: "2.8.2"
