packages:
  - "apps/*"
  - "packages/*"
  - "scripts"

catalog:
  "@anthropic-ai/sdk": "0.71.2"
  "@clickhouse/client": "1.12.1"
  "@iarna/toml": "3.0.0"
  "@types/chai": "4.3.20"
  "@types/mocha": "10.0.10"
  "@types/node": "20.19.24"
  chai: "4.5.0"
  mocha: "10.8.2"
  ts-node: "10.9.2"
  typescript: "5.9.3"
  yaml: "2.8.2"
