packages:
  - "apps/*"
  - "packages/*"
  - "scripts"

catalog:
  "@anthropic-ai/sdk": "0.71.2"
  "@clickhouse/client": "1.12.1"
  "@grpc/grpc-js": "1.14.3"
  "@grpc/proto-loader": "0.8.0"
  "@iarna/toml": "3.0.0"
  "@opentelemetry/otlp-transformer": "0.211.0"
  "@types/chai": "4.3.20"
  "@types/hast": "3.0.4"
  "@types/js-yaml": "4.0.9"
  "@types/mocha": "10.0.10"
  "@types/node": "20.19.33"
  axios: "1.7.9"
  chai: "4.5.0"
  eslint: "9.39.2"
  eslint-config-next: "16.1.6"
  github-slugger: "2.0.0"
  js-yaml: "4.1.1"
  mermaid: "11.12.0"
  mocha: "10.8.2"
  next: "16.1.6"
  posthog-node: "5.21.0"
  ts-node: "10.9.2"
  typescript: "5.9.3"
  yaml: "2.8.2"
