/// <reference types="node" />
/// <reference types="mocha" />
/// <reference types="chai" />
/**
 * End-to-end tests for S3Queue runtime secret resolution
 *
 * These tests verify that:
 * 1. mooseEnvSecrets markers are correctly generated by TypeScript/Python libraries
 * 2. Rust CLI correctly resolves the markers from environment variables
 * 3. Error messages include field names when environment variables are missing
 * 4. Tables without credentials (public buckets) work correctly
 */

import { spawn, ChildProcess } from "child_process";
import { expect } from "chai";
import * as path from "path";

// Import test utilities
import { TIMEOUTS, TEMPLATE_NAMES, APP_NAMES } from "./constants";

import {
  stopDevProcess,
  waitForServerStart,
  createTempTestDirectory,
  setupTypeScriptProject,
  setupPythonProject,
  removeTestProject,
} from "./utils";

const CLI_PATH = path.resolve(__dirname, "../../../target/debug/moose-cli");
const MOOSE_LIB_PATH = path.resolve(
  __dirname,
  "../../../packages/ts-moose-lib",
);
const MOOSE_PY_LIB_PATH = path.resolve(
  __dirname,
  "../../../packages/py-moose-lib",
);

describe("S3Queue Runtime Secret Resolution", () => {
  // Note: Testing missing environment variables is better done as a Rust unit test
  // because the CLI behavior on missing env vars during startup can vary.
  // See apps/framework-cli/src/utilities/secrets.rs for unit tests.

  describe("TypeScript - With Environment Variables", () => {
    let devProcess: ChildProcess | null = null;
    let TEST_PROJECT_DIR: string;

    before(async function () {
      this.timeout(TIMEOUTS.TEST_SETUP_MS);

      // Create temporary directory
      TEST_PROJECT_DIR = createTempTestDirectory("ts-s3-secrets-set");

      // Setup TypeScript project
      await setupTypeScriptProject(
        TEST_PROJECT_DIR,
        TEMPLATE_NAMES.TYPESCRIPT_TESTS,
        CLI_PATH,
        MOOSE_LIB_PATH,
        APP_NAMES.TYPESCRIPT_TESTS,
        "npm",
      );

      // Start dev server WITH the required environment variables set
      devProcess = spawn(CLI_PATH, ["dev"], {
        stdio: "pipe",
        cwd: TEST_PROJECT_DIR,
        env: {
          ...process.env,
          // Set dummy credentials for testing
          TEST_AWS_ACCESS_KEY_ID: "test-access-key-id",
          TEST_AWS_SECRET_ACCESS_KEY: "test-secret-access-key",
        },
      });

      await waitForServerStart(
        devProcess,
        TIMEOUTS.SERVER_STARTUP_MS,
        "started successfully",
        "http://localhost:4000",
      );
    });

    after(async function () {
      this.timeout(TIMEOUTS.CLEANUP_MS);
      await stopDevProcess(devProcess);
      removeTestProject(TEST_PROJECT_DIR);
    });

    it("should start successfully when environment variables are set", async function () {
      this.timeout(TIMEOUTS.TEST_SETUP_MS);

      // If we got here, the server started successfully
      // Verify the process is still running
      expect(devProcess?.killed).to.be.false;
    });
  });

  describe("Python - With Environment Variables", () => {
    let devProcess: ChildProcess | null = null;
    let TEST_PROJECT_DIR: string;

    before(async function () {
      this.timeout(TIMEOUTS.TEST_SETUP_MS);

      // Create temporary directory
      TEST_PROJECT_DIR = createTempTestDirectory("py-s3-secrets-set");

      // Setup Python project
      await setupPythonProject(
        TEST_PROJECT_DIR,
        TEMPLATE_NAMES.PYTHON_TESTS,
        CLI_PATH,
        MOOSE_PY_LIB_PATH,
        APP_NAMES.PYTHON_TESTS,
      );

      // Start dev server WITH the required environment variables set
      devProcess = spawn(CLI_PATH, ["dev"], {
        stdio: "pipe",
        cwd: TEST_PROJECT_DIR,
        env: {
          ...process.env,
          VIRTUAL_ENV: path.join(TEST_PROJECT_DIR, ".venv"),
          PATH: `${path.join(TEST_PROJECT_DIR, ".venv", "bin")}:${process.env.PATH}`,
          // Set dummy credentials for testing
          TEST_AWS_ACCESS_KEY_ID: "test-access-key-id",
          TEST_AWS_SECRET_ACCESS_KEY: "test-secret-access-key",
        },
      });

      await waitForServerStart(
        devProcess,
        TIMEOUTS.SERVER_STARTUP_MS,
        "started successfully",
        "http://localhost:4000",
      );
    });

    after(async function () {
      this.timeout(TIMEOUTS.CLEANUP_MS);
      await stopDevProcess(devProcess);
      removeTestProject(TEST_PROJECT_DIR);
    });

    it("should start successfully when environment variables are set", async function () {
      this.timeout(TIMEOUTS.TEST_SETUP_MS);

      // If we got here, the server started successfully
      expect(devProcess?.killed).to.be.false;
    });
  });
});
