import { ACCESS_ROLE_ADMIN_DEBUG } from "agent-contracts";
import { AuthError } from "next-auth";
import { redirect } from "next/navigation";
import type { JSX } from "react";
import { signIn } from "@/auth";
import { getVisibleLocalMockUsers } from "./local-auth";

interface LocalLoginFormProps {
  errorMessage?: string;
}

export function LocalLoginForm({
  errorMessage,
}: LocalLoginFormProps): JSX.Element {
  const localMockUsers = getVisibleLocalMockUsers();

  return (
    <div className="space-y-7">
      <form
        action={async (formData) => {
          "use server";

          const email = String(formData.get("email") ?? "");
          const password = String(formData.get("password") ?? "");

          try {
            await signIn("local-access", {
              email,
              password,
              redirectTo: "/",
            });
          } catch (error) {
            if (
              error instanceof AuthError &&
              (error.type === "CredentialsSignin" ||
                error.type === "CallbackRouteError")
            ) {
              redirect("/?login=invalid");
            }

            throw error;
          }
        }}
        className="space-y-5"
      >
        <div className="space-y-2.5">
          <label
            htmlFor="email"
            className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground"
          >
            Email
          </label>
          <input
            id="email"
            name="email"
            type="email"
            autoComplete="username"
            placeholder="user1@orgA.com"
            className="h-12 w-full rounded-2xl border bg-background/70 px-4 text-sm outline-none ring-offset-background transition placeholder:text-muted-foreground/70 focus-visible:ring-2 focus-visible:ring-ring"
            required
          />
        </div>

        <div className="space-y-2.5">
          <label
            htmlFor="password"
            className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground"
          >
            Password
          </label>
          <input
            id="password"
            name="password"
            type="password"
            autoComplete="current-password"
            placeholder="user1"
            className="h-12 w-full rounded-2xl border bg-background/70 px-4 text-sm outline-none ring-offset-background transition placeholder:text-muted-foreground/70 focus-visible:ring-2 focus-visible:ring-ring"
            required
          />
        </div>

        {errorMessage && (
          <div className="rounded-2xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">
            {errorMessage}
          </div>
        )}

        <button
          type="submit"
          className="h-12 w-full rounded-2xl bg-primary px-4 text-sm font-medium text-primary-foreground transition hover:opacity-95"
        >
          Sign in
        </button>
      </form>

      <div className="rounded-[1.6rem] border bg-muted/20 px-5 py-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.03)]">
        <div className="space-y-2">
          <div className="text-sm font-semibold tracking-tight">
            Mock accounts
          </div>
          <p className="max-w-sm text-sm leading-6 text-muted-foreground">
            Passwords are generated by{" "}
            <code className="rounded bg-background px-1 py-0.5 text-xs">
              pnpm env:prepare
            </code>{" "}
            and stored in{" "}
            <code className="rounded bg-background px-1 py-0.5 text-xs">
              packages/web-app/.env.local
            </code>
            .
          </p>
        </div>

        <div className="mt-5 space-y-3 text-sm">
          {localMockUsers.map((mockUser) => {
            const scopeLabel =
              mockUser.accessRole === ACCESS_ROLE_ADMIN_DEBUG ?
                "Admin access"
              : `${mockUser.orgName} access`;

            return (
              <div
                key={mockUser.id}
                className="rounded-2xl border bg-background/80 px-4 py-3"
              >
                <div className="text-sm font-medium leading-5">
                  {mockUser.email}
                </div>
                <div className="mt-1.5 text-sm leading-5 text-muted-foreground">
                  Password in{" "}
                  <code className="rounded bg-muted px-1 py-0.5 text-xs">
                    {mockUser.passwordEnvVar}
                  </code>
                  {" · "}
                  {scopeLabel}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
