"use client";

import * as React from "react";
import { cn } from "@/lib/utils";

interface InlineCodeProps {
  code: string;
  language: string;
  className?: string;
}

const darkModeStyles = cn(
  "dark:[&_.shiki]:!text-[var(--shiki-dark)]",
  "dark:[&_.shiki_span]:!text-[var(--shiki-dark)]",
);

/**
 * Inline code with syntax highlighting
 * Used for the Nextra-style `code{:lang}` syntax
 */
export function InlineCode({ code, language, className }: InlineCodeProps) {
  const [highlightedCode, setHighlightedCode] = React.useState<string>("");
  const [isLoading, setIsLoading] = React.useState(true);

  React.useEffect(() => {
    const loadHighlightedCode = async () => {
      try {
        const { codeToHtml } = await import("shiki");

        const html = await codeToHtml(code, {
          lang: language,
          themes: {
            light: "vitesse-light",
            dark: "vitesse-dark",
          },
        });

        // Extract just the code content, removing the pre/code wrapper
        // The output is usually: <pre class="shiki..."><code><span class="line">...</span></code></pre>
        const match = html.match(/<code[^>]*>([\s\S]*)<\/code>/);
        if (match?.[1]) {
          // Remove the line span wrapper for inline display
          const content = match[1].replace(
            /<span class="line">([\s\S]*?)<\/span>/g,
            "$1",
          );
          setHighlightedCode(content);
        } else {
          setHighlightedCode(code);
        }
        setIsLoading(false);
      } catch {
        // Fallback to plain text
        setHighlightedCode(code);
        setIsLoading(false);
      }
    };

    loadHighlightedCode();
  }, [code, language]);

  if (isLoading) {
    return (
      <code
        className={cn(
          "relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm not-prose",
          className,
        )}
      >
        {code}
      </code>
    );
  }

  return (
    <code
      className={cn(
        "relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm not-prose inline-flex items-center",
        darkModeStyles,
        className,
      )}
      data-language={language}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: HTML is generated by shiki syntax highlighter
      dangerouslySetInnerHTML={{ __html: highlightedCode }}
    />
  );
}
