name: 'Login to Docker Hub'
description: 'Authenticate with Docker Hub using 1Password credentials to avoid rate limits'
inputs:
  op-service-account-token:
    description: '1Password service account token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Load Docker Hub credentials from 1Password
      id: op-load-secret
      uses: 1password/load-secrets-action@v2
      with:
        export-env: false
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.op-service-account-token }}
        DOCKER_HUB_ACCESS_KEY: "op://drqe7p6legi6ug2ijq2fnrkmjq/Docker Hub - Bot/Access Token"
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: 514iceman
        password: ${{ steps.op-load-secret.outputs.DOCKER_HUB_ACCESS_KEY }}

