# This file was auto-generated by the framework. You can add data models or change the existing ones

from datetime import datetime

from moose_lib import (
    Key,
    OlapConfig,
)
from moose_lib.blocks import NullEngine
from moose_lib.dmv2 import (
    OlapTable,
)
from pydantic import BaseModel


class Items(BaseModel):
    order_id: Key[int]
    id: Key[int]
    updated_at: datetime

items_null = OlapTable[Items](
    "items_null",
    OlapConfig(
        engine=NullEngine(),
    ),
)