

# This file was auto-generated by the framework. You can add data models or change the existing ones
from typing_extensions import Literal
from app.db import models
import app.db.views as views
from app.workflows.generator import ingest_workflow, ingest_task
from moose_lib import QueryClient
from moose_lib.config.runtime import config_registry
from pydantic import BaseModel, Field
from typing import Optional, List, Literal

import app.api as api

app = api.app


BarAgg = views.BarAggregatedTable

