

# This file was auto-generated by the framework. You can add data models or change the existing ones
import app.db.models as models
import app.db.views as views

import app.api as api

app = api.api

