language = "typescript" # Must be typescript or python
description = "A typescript MooseStack project with a NextJS frontend (empty)."
post_install_print = """
Deploy on Boreal

The easiest way to deploy your MooseStack Applications is to use Boreal
from the creators of MooseStack.

https://boreal.cloud

---------------------------------------------------------

📂 Go to your project directory:
    $ cd {project_dir}/moose

📦 Install Dependencies:
    $ npm i

🛠️ Start dev server:
    $ moose dev

ℹ️ In another terminal window:
📂 Go to your frontend project:
    $ cd {project_dir}/frontend

📦 Install Dependencies:
    $ npm i

🛠️ Start frontend dev server:
	$ npm run dev
"""
visible=true
